export const STARTUP_INDUSTRIES = [
  "Agriculture & Food",
  "Artificial Intelligence",
  "Biotech",
  "Climate & Energy",
  "Commerce & Retail",
  "Construction Technology",
  "Consumer & Marketplace",
  "Cybersecurity",
  "Data & Analytics",
  "Defense Technology",
  "Developer Tools",
  "Education",
  "Fintech",
  "Gaming",
  "Hardware & Semiconductors",
  "Healthtech",
  "HR & Future of Work",
  "Industrial & Manufacturing",
  "Insurtech",
  "Legal & Compliance",
  "Logistics & Supply Chain",
  "Media & Creator Economy",
  "Mobility & Automotive",
  "Quantum Computing",
  "Real Estate & Proptech",
  "Robotics & Automation",
  "SaaS",
  "Space Technology",
  "Telecommunications",
  "Travel & Hospitality",
  "Web3 & Blockchain",
] as const;
